ex186a is

  f =>
    say "perform exit:"
    exit 0
    say "** not reachable code **"

  my_exit : Exit_Handler is
    redef exit(code u8) void =>
      io.err.println "*** user defined exit handler diverting exit $code ***"
      exit.type.abort

  exit my_exit ()->
    f
    say "** not reachable code **"

  say "continue even though exit was called..."
